### ISSUE TITLE
`path.basename` extension argument

### ISSUE THREAD

**Issue by RiskoZS** [truemedian/luvit-api-design#14]
As was mentioned in https://github.com/truemedian/luvit-api-design/pull/9#issuecomment-1050858085, `path.basename` is missing 2.x's `expected_ext` argument. However, perhaps we would like to consider ["an `exclude_extension` boolean instead of an `expected_ext` string param"](https://ptb.discord.com/channels/377572091869790210/468625729211334686/947260709799080026).

Arguments for:
* A simple boolean option will likely be more convenient in the majority of use cases, as one does not have to first extract the extension.

Arguments against:
* [A boolean option is inconsistent with the coreutils `basename` command, which takes a suffix to remove.](https://ptb.discord.com/channels/377572091869790210/468625729211334686/947276180069945394)

Discuss below.

**Comment by RiskoZS** [comment]
Here's a potential third option: If the argument is a string, treat it as the extension to remove (2.x behaviour). Otherwise, if it's `true`, remove *any* extension (proposed behaviour).

**Comment by truemedian** [comment]
I rather like that third option, since it provides the greatest amount of flexibility, and is not all that difficult to implement or understand.
