### ISSUE TITLE
URL vs URI

### ISSUE THREAD

**Issue by Bilal2453** [truemedian/luvit-api-design#18]
In the readme, it lists `url` as done but never makes a mention of a `uri` module. Yet in the std, we see `uri.lua` being implemented and never `url.lua`.

Not quite sure what was the intention there, but I don't think it makes much sense to only have one of the modules and not have the other. Having utilities for URLs is quite useful (and will probably need it for a proper HTTP module), while URI offers the abstracted utilities such as the percentEncode.

What should be done from here?

**Comment by truemedian** [comment]
URL is a subset of URI: `uri.lua` should be a spec-compliant implementation of [RFC 3986, "Uniform Resource Identifier (URI): Generic Syntax"](https://datatracker.ietf.org/doc/html/rfc3986)

> [1.1.3](https://datatracker.ietf.org/doc/html/rfc3986#section-1.1.3).  URI, URL, and URN
> A URI can be further classified as a locator, a name, or both.  The
   term "Uniform Resource Locator" (URL) refers to the subset of URIs
   that, in addition to identifying a resource, provide a means of
   locating the resource by describing its primary access mechanism
   (e.g., its network "location").  The term "Uniform Resource Name"
   (URN) has been used historically to refer to both URIs under the
   "urn" scheme [[RFC2141](https://datatracker.ietf.org/doc/html/rfc2141)], which are required to remain globally unique
   and persistent even when the resource ceases to exist or becomes
   unavailable, and to any other URI with the properties of a name.

**Comment by Bilal2453** [comment]
I am aware of that. But if there will be no `url.lua` module, then the readme needs to be fixed:
![image](https://user-images.githubusercontent.com/38175840/173182992-b255c3f7-f5aa-45b1-a2bc-b02677eb464a.png)
This should be renamed to `uri`.

I am also arguing that we need to implement both, the subset (URL) and the abstract (URI).

**Comment by truemedian** [comment]
Implementing URI is implementing URL, because URL is a sub specification of RFC 3986. But I will add the renaming note.
