### ISSUE TITLE
[Proposal]: Merge https into http

### ISSUE THREAD

**Issue by Bilal2453** [truemedian/luvit-api-design#21]
Reading the README, I see it implying that coro-http is going to be split into multiple modules: http, https and http-header. Not sure if that is indeed what the README is trying to say, but here is what I think should be done.

The `https` module should be merged into a `http` module, while having a separate `http-header` module that has headers related utilities. The new `http` module should be similar-ish to coro-http, with the exception of removed headers utilities, as well as with better `fetch`-like API and better overall coverage of the HTTP spec.

If that was indeed the intention, `https` should be moved from the "Reimplementations or Reworkings" section into the "To Be Removed" section, with a comment `(merged into http)`.
Otherwise, what would be your ideas? And how should the README be edited to better reflect those ideas?

**Comment by truemedian** [comment]
None of the libraries are being removed, as that would mean removing http/https support from luvit.

As for their merging, that depends on how their new counterparts get implemented. For now the comment on coro-http about merging all of them is sufficient
