### ISSUE TITLE
OOP Timer

### ISSUE THREAD

**Issue by RiskoZS** [truemedian/luvit-api-design#7]
[As I have mentioned on Discord](https://ptb.discord.com/channels/377572091869790210/468625729211334686/944987156731031682), it would be neat if the `timer` module returned objects which wrap the `uv_timer_t` handles so that one can call `:clear()` (or similar) on them directly without having to use `timer.clearInterval()`. I'd have PR'd this already, but the class system (if there even is going to be one in the first place) isn't finalized yet, so this Issue is just a reminder to revisit this once that's done.

**Comment by truemedian** [comment]
I just realized that we don't actually need this here. the `uv_timer_t` that is returned is a luv object, so you can just call `:stop()` on it

**Comment by RiskoZS** [comment]
[`timer.clearTimeout` does a bit more than that, though](https://github.com/luvit/luvit/blob/3f328ad928eb214f6438dd25fb9ee8b5c1e9255c/deps/timer.lua#L112-L116). It checks whether the timer is closing, and then stops and closes the handle too.

**Comment by truemedian** [comment]
fair, but timer doesn't really need that overhead for something that simple. In any case, even the old Timer class doesn't actually do anything more than call stop

**Comment by RiskoZS** [comment]
What do you mean by "old Timer class"? Luvit's 2.x `timer` isn't a class, unless you're referring to something else...?

**Comment by truemedian** [comment]
I mean [this](https://github.com/luvit/luvit/blob/master/deps/timer.lua#L38-L80).
